[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "bec_ipython_client"
version = "2.9.6"
description = "BEC IPython client"
requires-python = ">=3.10"
classifiers = [
    "Development Status :: 3 - Alpha",
    "Programming Language :: Python :: 3",
    "Topic :: Scientific/Engineering",
]
dependencies = [
    "bec_lib",
    "numpy",
    "requests",
    "typeguard",
    "ipython",
    "rich",
    "pyepics",
    "h5py",
]

[project.optional-dependencies]
dev = [
    "black~=24.0",
    "isort",
    "coverage",
    "pylint",
    "pytest",
    "pytest-random-order",
    "pytest-timeout",
    "pytest-redis",
    "pytest-retry",
    "pytest-bec-e2e",
]

[project.scripts]
bec = "bec_ipython_client.main:main"

[project.urls]
"Bug Tracker" = "https://gitlab.psi.ch/bec/bec/issues"
Homepage = "https://gitlab.psi.ch/bec/bec"

[tool.hatch.build.targets.wheel]
include = ["*"]

[tool.black]
line-length = 100
skip-magic-trailing-comma = true

[tool.isort]
profile = "black"
line_length = 100
multi_line_output = 3
include_trailing_comma = true
known_first_party = ["bec_lib", "bec_server", "bec_ipython_client"]
