[project]
name = "lego-handlers"
version = "1.0.0"
description = "Add your description here"
authors = [{ name = "Tomperez98", email = "tomasperezalvarez@gmail.com" }]
dependencies = [
    "result>=0.16.1",
]
readme = "README.md"
requires-python = ">= 3.10"

[project.urls]
Documentation = "https://github.com/Tomperez98/lego-handlers#readme"
Issues = "https://github.com/Tomperez98/lego-handlers/issues"
Source = "https://github.com/Tomperez98/lego-handlers"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.rye]
managed = true
dev-dependencies = [
    "pytest>=8.1.1",
    "mypy>=1.10.0",
    "pytest-cov>=5.0.0",
    "pytest-asyncio>=0.23.6",
    "toml>=0.10.2",
]

[tool.rye.scripts]
check-types = "dmypy run --timeout 60 -- src tests"
new-release = "python scripts/new-release.py"

[tool.ruff]
unsafe-fixes = true
line-length = 88
fix = false

[tool.ruff.lint]
preview = true
ignore = [
    "ANN101",
    "D203",
    "D212",
    "COM812",
    "COM819",
    "D206",
    "E501",
    "ISC001",
    "Q000",
    "Q001",
    "Q002",
    "Q003",
    "W191",
    "UP040",
    "CPY001",
    "D101",
    "D102",
    "D107",
    "D103",
]
select = ["ALL"]

[tool.ruff.lint.flake8-tidy-imports.banned-api]
enum = { msg = "`enum` is banned: Python enums are not allowed. Use typing.Literal and typing.TypeAlias to build enums" }

[tool.ruff.lint.per-file-ignores]
"tests/*.py" = ["INP001", "S101", "D"]
"scripts/*" = ["INP001"]

[tool.ruff.lint.flake8-tidy-imports]
ban-relative-imports = "all"

[tool.ruff.lint.flake8-quotes]
inline-quotes = "double"

[tool.pytest.ini_options]
testpaths = ["tests"]
xfail_strict = true
addopts = [
    "--import-mode=importlib",
    "--strict-markers",
    "--cov-config=pyproject.toml",
]
markers = [
    "unit: mark unittest.",
]
asyncio_mode = "auto"

[tool.mypy]
mypy_path = "src"

[tool.hatch.metadata]
allow-direct-references = true

[tool.hatch.build.targets.wheel]
packages = ["src/lego_handlers"]
