[tool.poetry]
name = "furrow1k"
version = "0.1.15"
description = "Help calculate percentage of salary to contribute to 401k"
authors = ["Frank Cao"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12.2"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
furrow1k = "furrow1k.furrow1k:main"
