[tool.poetry]
name = "digrdf"
version = "0.1.3"
description = "RDF Schema Diagram creation tool"
authors = ["Lawson Lewis <lawson@kurrawong.ai>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
pyvis = "^0.3.2"

[tool.poetry.group.dev.dependencies]
black = "^24.4.2"
isort = "^5.13.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
