[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "autorunpy"
version = "8.0.0"
authors = [{ name = "Mahdi Mir", email = "imahdimir@gmail.com" }]
description = "Tools for auto running python scripts"
readme = "README.md"
license = { file = "LICENSE" }
dependencies = [
]
