[tool.poetry]
name = "midori"
version = "1.0.0"
description = "ğŸƒ streamline remote software engineering experiments"
authors = ["Xingwen Xiao <xingwen.xiao@student.uva.nl>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
paramiko = "^3.4.0"


[tool.poetry.group.dev.dependencies]
ruff = "^0.4.2"
pre-commit = "^3.7.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
