[tool.poetry]
name = "netlink-keepass"
version = "0.6.2"
description = "Tools to work with (Py)KeePass"
authors = ["Bernhard Radermacher <bernhard.radermacher@netlink-consulting.com>"]
repository = "https://gitlab.com/netlink_python/netlink-keepass.git"
packages = [ { include = "netlink/keepass" } ]

[tool.poetry.scripts]
netlink-keepass-rest-reader = 'netlink.keepass.cli:reader_cli'
netlink-keepass-fernet-token = 'netlink.keepass.cli:fernet_token_cli'
netlink-keepass-rest-get = 'netlink.keepass.cli:rest_get_cli'
netlink-keepass-rest-shutdown = 'netlink.keepass.cli:rest_shutdown_cli'


[tool.poetry.dependencies]
python = ">=3.8.1,<3.13"
click = ">=8.1.7"
pykeepass = ">=4.0.6"
fastapi = ">=0.109.0"
uvicorn = ">=0.27.0"
cryptography = ">=42.0.1"

[tool.poetry.dev-dependencies]
black = ">=24.1.1"
uvicorn = {extras = ["standard"], version = ">=0.27.0"}
pytest = "^8.0.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
